spring:
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: manager-service
          service-host-type: ip
        url: http://localhost:8888


  application:
    name: manager-app
  datasource:
    username: manager
    url: jdbc:postgresql://localhost:5433/manager
    password: password
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: 0nTCxTeSBDKDniJkdlAKn7JEJGPBcQtB
            scope:
                - openid
                - microprofile-jwt
                - view_catalogue
                - edit_catalogue


services:
  catalogue:
    uri: http://localhost:8081
    registration-id: keycloak


management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'