spring:
  security:
    user:
      name: catalogue_service_user
      password: password
      roles:
        - SERVICE
  application:
    name: catalogue-service
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: salas
    password: password
  jpa:
    show-sql: true
  flyway:

    schemas:
      - public
      - catalogue

server:
  port: 8081

logging:
  level:
    sql: info

