spring:
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: catalogue-service
          service-host-type: ip
        url: http://localhost:8888

  application:
    name: catalogue-service
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: salas
    password: password
  jpa:
    show-sql: true


  flyway:
    schemas:
      - public
      - catalogue

server:
  port: 8081

logging:
  level:
    sql: info

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}

