spring:
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: feedback-service
          service-host-type: ip
        url: http://localhost:8888
  application:
    name: feedback-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/feedback
#
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8082/realms/selmag


server:
  port: 8085

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
