spring:
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: customer-service
          service-host-type: ip
        url: http://localhost:8888
  application:
    name: customer-app
#
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8082/realms/selmag
#            user-name-attribute: preferred_username
#        registration:
#          keycloak:
#            client-id: customer-app
#            client-secret: ldOv49attIsQtJygyz22WgAEcYUKlXOQ
#            scope:
#              - openid
#              - view_catalogue


services:
  catalogue:
    uri: http://localhost:8081
  feedback:
    uri: http://localhost:8085

server:
  port: 8084

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}


